const ResponseMessage = {
    USER_CREATE_SUCCESS: 'User created successfully',
    USER_LOGIN_SUCCESS: 'User login successfully',
    USER_ALREADY_EXIST_EMAIL: "Email already exists",
    PASSWORD_AND_CONFIRM_PASSWORD: "Password & confirm password does not match",
    INVALID_PASSWORD: 'Invalid Credentials',
    INTERNAL_SERVER_ERROR: "Internal server error",
    USER_NOT_FOUND: "User not found",
    EMAIL_NOT_EXIST: 'Email not exists',
    PLEASE_VERIFY_PROFILE: "Please verify your profile",
    ACCOUNT_DELETE: "Your account was deleted",
    RESET_PASSWORD_MAIL: "OTP has sent on your email successfully",
    OTP_VERIFIED_SUCCESS: 'OTP verified successfully',
    OTP_INVALID: 'Please enter valid OTP',
    RESEND_OTP_SUCCESS: 'OTP send successfully',
    SECRET_PHASE_KEY_ADD_SUCCESS: 'Secret phase key added successfully',
    NEW_PASSWORD_SAME_AS_OLD: 'New password can not be same as existing password',
    RESET_PASSWORD_SUCCESS: 'Password reset successfully',
    KYB_SUBMIT_SUCCESS: 'KYB submitted successfully',
    KYB_UPDATE_SUCCESS: 'KYB updated successfully',
    KYC_SUBMIT_SUCCESS: 'KYC submitted successfully',
    KYC_UPDATE_SUCCESS: 'KYC updated successfully',
    KYC_KYB_DETAIL_FETCH_SUCCESS: 'KYC and KYB detail fetch successfully',
    STORE_SETUP_SUCCESS: 'Store setup successfully',
    STORE_UPDATE_SUCCESS: 'Store updated successfully',
    CUSTOMIZE_STORE_SETUP_SUCCESS: 'Customize store setup successfully',
    CUSTOMIZE_STORE_UPDATE_SUCCESS: 'Customize store updated successfully',
    TOKEN_NOT_AUTHORIZED: "Token not authorized",
    TOKEN_NOT_VALID_AUTHORIZED: "Token not valid authorized",
    ADMIN_REGISTER_SUCCESS: "Admin registered successfully",
    ADMIN_LOGIN_SUCCESS: 'Admin Login successfully',
    ADMIN_NOT_FOUND: "Admin not found",
    OLD_PASSWORD_INCORRECT: 'Old Password is Incorrect',
    OLD_PASSWORD_NEW_PASSWORD_SAME: 'New Password must be different from the Old Password',
    PASSWORD_CHANGE_SUCCESS: 'Password changed successfully',
    USER_LIST_FETCH_SUCCESS: 'User list fetched successfully',
    USER_DETAIL_FETCH_SUCCESS: 'User details fetched successfully',
    ASSET_CREATE_SUCCESS: 'Asset created successfully',
    ASSET_LIST_FETCH_SUCCESS: 'Asset list fetched successfully',
    ASSET_DETAILS_FETCH_SUCCESS: 'Asset details fetched successfully',
    ASSET_UPDATE_SUCCESS: 'Asset updated successfully',
    ASSET_DELETE_SUCCESS: 'Asset deleted successfully',
    PRIVACY_POLICY_ADD_SUCCESS: 'Privacy policy added successfully',
    PRIVACY_POLICY_UPDATE_SUCCESS: 'Privacy policy updated successfully',
    TERMS_AND_CONDITION_ADD_SUCCESS: 'Terms and conditions added successfully',
    TERMS_AND_CONDITION_UPDATE_SUCCESS: 'Terms and conditions updated successfully',
    CMS_DETAIL_FETCH_SUCCESS: 'CMS detail fetch successfully',
    ADMIN_PROFILE_UPDATE_SUCCESS: "Admin profile updated successfully",
    PAYMENT_REQUEST_ADD_SUCCESS: "Payment request added successfully",
    REQUEST_PAYMENT_DETAIL_FETCH_SUCCESS: "Request payment detail fetch successfully",
    CATEGORY_CREATE_SUCCESS: 'Category created successfully',
    CATEGORY_LIST_FETCH_SUCCESS: 'Category list fetched successfully',
    CATEGORY_UPDATE_SUCCESS: 'Category updated successfully',
    CATEGORY_DELETE_SUCCESS: 'Category deleted successfully',
    BUSINESS_CREATE_SUCCESS: 'Business created successfully',
    BUSINESS_LIST_FETCH_SUCCESS: 'Business list fetched successfully',
    BUSINESS_UPDATE_SUCCESS: 'Business updated successfully',
    BUSINESS_DELETE_SUCCESS: 'Business deleted successfully',
    KYC_APPROVED_SUCCESS: 'Kyc approved successfully',
    KYC_REJECT_SUCCESS: 'Kyc rejected successfully',
    KYB_APPROVED_SUCCESS: 'Kyb approved successfully',
    KYB_REJECT_SUCCESS: 'Kyb rejected successfully',
    FAQ_CREATE_SUCCESS: 'Faq created successfully',
    FAQ_LIST_FETCH_SUCCESS: 'Faq list fetched successfully',
    FAQ_UPDATE_SUCCESS: 'Faq updated successfully',
    FAQ_DELETE_SUCCESS: 'Faq deleted successfully',
    COLOR_CREATE_SUCCESS: 'Color created successfully',
    COLOR_LIST_FETCH_SUCCESS: 'Color list fetched successfully',
    COLOR_UPDATE_SUCCESS: 'Color updated successfully',
    COLOR_DELETE_SUCCESS: 'Color deleted successfully',
    FONT_CREATE_SUCCESS: 'Font created successfully',
    FONT_LIST_FETCH_SUCCESS: 'Font list fetched successfully',
    FONT_UPDATE_SUCCESS: 'Font updated successfully',
    FONT_DELETE_SUCCESS: 'Font deleted successfully',
    CONTACT_DETAILS_SAVE_SUCCESS: 'Contact details save successfully',
    CONTACT_DETAILS_UPDATE_SUCCESS: 'Contact details updated successfully',
    CONTACT_DETAIL_FETCH_SUCCESS: "Contact detail fetch successfully",
    TRANSACTION_STATUS_UPDATE_SUCCESS: "Transaction status updated successfully",
    APPLICANT_ACCOUNT_NOT_CREATED:"Something went wrong while creating applicant account",
    APPLICANT_TOKEN_FOUND:"Applicant token fetched successfully",
    APPLICANT_TOKEN_NOT_FOUND:"Applicant token not found",
    KYC_DETAILS_UPDATED:"Kyc details updated successfully",
    ACCESS_TOKEN_GENERATED:"Access token generated successfully",
    SOMETHING_WENT_WRONG:"Something went wrong",
    APPLICANT_DETAILS_FETCHED:"Applicant details fetched successfully",
    KYC_AND_KYB_APPROVED_SUCCESS: 'KYC and KYB approved successfully',
    KYC_AND_KYB_REJECT_SUCCESS: 'KYC and KYB rejected successfully',
    KYC_KYB_STATUS_FETCHED:"Kyc and kyb status fetched successfully",
    DASHBAORD_TILES_FETCHED:"Dashboard data fetched successfully",
    WEEKLY_USER_REGISTRATION:"Weekly user registrations fetched successfully",
    STORE_FROM_CATEGORY_FETCHED:"Store list from category fetched successfully",
    STORE_NOT_FOUND:"Store not found",
    FCM_TOKEN_UPDATE_SUCCESS:"Fcm token updated successfully",
    TRANSACTION_CANCEL_SUCCESSFULLY:"Transaction cancelled successfully",
    GET_INVOICE_NUMBER_SUCCESS:"Get invoice number successfully",
    PUSH_NOTIFICATION_SEND_SUCCESS:"Push notification send successfully",
    NOTIFICATION_LIST_FETCH_SUCCESS:"Notification list fetch successfully",
    TRANSACTION_DETAIL_FETCH_SUCCESS: "Transaction detail fetch successfully",
    RESEND_OTP_NOT_SEND: "Resend OTP not send",
    LAST_TOKEN_STORE_SUCCESS: "Last token stored successfully",
    LAST_TOKEN_FETCH_SUCCESS: "Last token fetch successfully",
    DELETE_ACCOUNT_REQUEST_SEND_SUCCESS: "Delete account request send successfully",
    ACCOUNT_DELETE_SUCCESS: "Account deleted successfully",
    DELETE_ACCOUNT_REQUEST_LIST_FETCH_SUCCESS: "Delete account request list fetch successfully",
}
export { ResponseMessage }