export default {
  emptyEmail: 'Please enter email',
  invalidEmail: 'Please enter valid email',
  emptyPassword: 'Please enter password (Ex. Jhon@123)',
  invalidPassword:
    'Password must be 8-25 characters with 1 uppercase, 1 lowercase, 1 special character and 1 number',
  emptyConfirmPassword: 'Please enter confirm password',
  confirmPasswordMatch: 'Password & confirm password does not match',
  emptyConfirmNewPassword: 'Please enter confirm new password',
  invalidNewPasswordMatch: 'New password & confirm new password does not match',
  confirmNewPasswordMatch: 'Password & confirm new password does not match',
  emptyMobile: 'Please enter mobile number',
  invalidMobile: 'Please enter valid mobile number',
  emptyOTP: 'Please enter OTP',
  invalidOTP: 'Please enter valid OTP',
  emptyCountry: 'Please select country',
  emptyCompanyName: 'Please enter company name',
  companyNameLength: 'Company name must contain atleast 2 characters',
  invalidCompanyName: 'Please enter valid company name',
  emptyTaxId: 'Please enter tax id',
  invalidTaxId: 'Please enter valid tax id',
  emptyBusinessId: 'Please enter business id',
  invalidBusinessId: 'Please enter valid business id',
  emptyName: 'Please enter name',
  nameLength: 'Name must contain atleast 2 characters',
  invalidName: 'Please enter valid name',
  emptyDocument: 'Please select type of document',
  emptyUniqueId: 'Please enter unique id',
  invalidUniqueId: 'Please enter valid unique id',
  emptyPhoto: 'Please upload front & back photo',
  emptyFrontPhoto: 'Please upload front photo',
  emptyBackPhoto: 'Please upload back photo',
  emptyTypeBusiness: 'Please select type of business',
  emptyCategory: 'Please select category',
  emptyBusinessName: 'Please enter business name',
  businessNameLength: 'Business name must contain atleast 3 characters',
  invalidBusinessName: 'Please enter valid business name',
  emptyContactNumber: 'Please enter contact number',
  invalidContactNumber: 'Please enter valid contact number',
  emptyCity: 'Please enter city',
  invalidCity: 'Please enter valid city',
  emptyPincode: 'Please enter pincode',
  invalidPincode: 'Please enter valid pincode',
  emptyAddress: 'Please enter address',
  invalidAddress: 'Please enter valid address',
  emptyLogo: 'Please upload logo',
  emptyCoverImage: 'Please upload cover photo',
  emptyNewPassword: 'Please enter new password (Ex. Jhon@123)',
  invalidNewPassword:
    'New password must be 8-25 characters with 1 uppercase, 1 lowercase, 1 special character and 1 number',
  emptyOldPassword: 'Please enter old password (Ex. Jhon@123)',
  invalidOldPassword:
    'Old password must be 8-25 characters with 1 uppercase, 1 lowercase, 1 special character and 1 number',
  emptyAmount: 'Please enter amount',
  invalidAmount: `Amount can't be decimal`,
  zeroAmount: `Amount can't be zero`,
  emptyCurrency: 'Please select currency',
  emptyStellarAddress: 'Please enter wallet address',
  invalidStellarAddress: 'Please enter valid wallet address',
  emptyFirstName: 'Please enter first name',
  firstNameLength: 'First name must contain atleast 2 characters',
  invalidFirstName: 'Please enter valid first name',
  emptyLastName: 'Please enter last name',
  lastNameLength: 'Last name must contain atleast 2 characters',
  invalidLastName: 'Please enter valid last name',
  emptyBirthDate: 'Please enter date of birth',
  invalidBirthDate: 'Please enter valid date of birth (dd/mm/yyyy)',
  emptyMemo: 'Please enter memo',
  emptyAmountCurrency: 'Please enter amount & select currency',

  invalidPasscode: 'Invalid passcode',
  emptyFonts: 'Please select custom fonts',
  emptyColors: 'Please select colors',
  emptyTheme: 'Please select theme',
  emptyBusinessPhoto: 'Please select Business Photo ID',
};
