//baseURL : 'https://stellarxplutope.appworkdemo.com/api/user',
//imageURL: 'https://stellarxplutope.appworkdemo.com/api/public/',
//webviewURL: 'https://stellarxplutope.appworkdemo.com/verification/',

/**
 baseURL: 'https://merchant.plutope.app/api/user',
 imageURL: 'https://merchant.plutope.app/api/public/',
 webviewURL: 'https://merchant.plutope.app/verification/',
 */

export default {
  baseURL: 'https://merchant.plutope.app/api/user/',
  imageURL: 'https://merchant.plutope.app/api/public/',
  webviewURL: 'https://merchant.plutope.app/verification/',
  // baseURL: 'https://stellarxplutope.appworkdemo.com/api/user/',
  // imageURL: 'https://stellarxplutope.appworkdemo.com/api/public/',
  commonURL: 'https://merchant.plutope.app/api/common/',
  testnetURL: 'https://horizon-testnet.stellar.org',
  mainnetURL: 'https://horizon.stellar.org',
  // webviewURL: 'https://stellarxplutope.appworkdemo.com/verification/',
  transactionUrl: 'https://stellarchain.io/transactions/',
  coinGeckoCurrency:
    'https://api.coingecko.com/api/v3/coins/markets?vs_currency=USD',
  onfidoToken: 'api_sandbox.JewIfAQ847T.DRizAKzaOYJ-j-NBEDUn924m-ao4y09M',
  getStellarTransaction: 'https://horizon.stellar.org/transactions/',
  onfidoUrl: 'https://api.eu.onfido.com/v3.6/',
  moonpayApiKey: 'pk_live_wHatk1dIrr0RKpVKmwA9v4uReO7yrIPN',
  mode: 'public', //testnet public
  searchAssetURL: 'https://api.stellar.expert/explorer/',
  moonpaySellWebView:
    'https://sell.moonpay.com/?apiKey=pk_live_wHatk1dIrr0RKpVKmwA9v4uReO7yrIPN&theme=light&defaultBaseCurrencyCode=xlm&baseCurrencyAmount=0.05&colorCode=%237d01ff',
  moonpayBuyWebView:
    'https://buy.moonpay.com/?apiKey=pk_live_wHatk1dIrr0RKpVKmwA9v4uReO7yrIPN&theme=light&defaultQuoteCurrencyCode=xlm&baseCurrencyAmount=0.05&colorCode=%237d01ff',
  register: 'register',
  login: 'login',
  verifyOtp: 'verify-otp',
  resendOtp: 'resend-otp',
  forgotPassword: 'forgot-password',
  resetPassword: 'reset-password',
  userKyb: 'user-kyb',
  userKyc: 'user-kyc',
  getKybKycStatus: 'get-submit-kyb-kyc',
  setupStore: 'setup-store',
  setupCustomizeStore: 'setup-customize-store',
  editKyb: 'user-edit-kyb',
  editKyc: 'user-edit-kyc',
  editStore: 'edit-setup-store',
  editCustomizeStore: 'edit-customize-store',
  changePassword: 'change-password',
  addPhraseKey: 'add-secret-phase-key',
  getAssetList: 'get-asset-list-for-user',
  requestPayment: 'request-payment',
  getDecryptKey: 'decrypt-secret-key',
  getRequestPaymentDetails: 'get-request-payment-details',
  getAllCategory: 'get-all-category',
  getAllBusinessType: 'get-all-business-type',
  getAllFaq: 'get-all-faq',
  getContactDetails: 'get-contact-details',
  getAllColor: 'get-all-color',
  getAllFont: 'get-all-font',
  updateTransactionStatus: 'update-transaction-status',
  getCms: 'get-cms',
  updateKycDetail: 'update-kyc-details',
  kyckybStatus: 'get-kyc-kyb-status',
  cancelPayment: 'cancel-transaction',
  getInvoiceNumber: 'get-invoice-number',
  updateFcmToken: 'update-fcm-token',
  sendPushNotification: 'send-request-payment-push-notification',
  notificationList: 'get-user-notification-list',
  deleteAccount: 'send-delete-account-request',
};
