import {font, color} from '@theme/index';
import {Dimensions, StyleSheet} from 'react-native';

const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  addressText: {
    fontSize: 12,
    fontFamily: font.interLight,
    color: color.white,
    marginTop: 4,
  },
  tab1Divider: {
    flexDirection: 'row',
    marginTop: 16,
  },
  downloadIcon: {
    transform: [{rotate: '180deg'}],
  },
  tab2View: {
    flex: 1,
    height: 140,
    backgroundColor: color.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    marginLeft: 16,
    shadowColor: color.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  tabText: {
    fontSize: 14,
    fontFamily: font.interRegular,
    color: color.black,
    marginTop: 14,
    textAlign: 'center',
    paddingHorizontal: 5,
    lineHeight: 18,
  },
  tab1View: {
    flex: 1,
    height: 140,
    backgroundColor: color.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    shadowColor: color.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  tabDivider: {
    flexDirection: 'row',
    top: -30,
    paddingHorizontal: 20,
    // marginTop: 36,
  },
  assetDivider: {
    flexDirection: 'row',
    marginHorizontal: 20,
  },
  seeText: {
    fontSize: 13,
    fontFamily: font.interRegular,
    color: color.black,
    textDecorationLine: 'underline',
  },
  assetText: {
    fontSize: 18,
    fontFamily: font.violetSansRegular,
    color: color.black,
    flex: 1,
  },
  borderStyle: {
    // borderWidth: 0.3,
    // borderColor: color.borderGray,
    // marginBottom: 24,
    height: StyleSheet.hairlineWidth,
    backgroundColor: color.black,
    marginHorizontal: 20,
    marginBottom: 30,
    opacity: 0.5,
  },
  flatlistContainer: {
    flexGrow: 1,
    paddingHorizontal: 20,
  },
  withdrawText: {
    fontSize: 16,
    fontFamily: font.violetSansRegular,
    color: color.black,
    marginLeft: 8,
  },
  withdrawContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 21,
    paddingVertical: 13,
    backgroundColor: color.greenShade,
    borderRadius: 30,
  },
  converter: {
    fontSize: 20,
    fontFamily: font.interLight,
    color: color.white,
    marginTop: 4,
    textAlign: 'center',
  },
  priceText: {
    fontSize: 60,
    fontFamily: font.violetSansRegular,
    color: color.white,
    marginTop: 4,
    marginBottom: 5,
  },
  balanceText: {
    fontSize: 20,
    fontFamily: font.interLight,
    color: color.white,
    textAlign: 'center',
  },
  main: {
    // flex: 1,
  },
  balanceDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 31,
    paddingBottom: 60,
    backgroundColor: color.blueShade,
    borderBottomStartRadius: 15,
    borderBottomEndRadius: 15,
    paddingHorizontal: 20,
  },
  scrollStyle: {
    flexGrow: 1,
  },
  userIcon: {
    height: 40,
    width: 40,
    resizeMode: 'cover',
    borderRadius: 20,
    backgroundColor: color.borderGray,
  },
  userImage: {
    height: 50,
    paddingRight: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scan: {
    height: 50,
    paddingLeft: 15,
    paddingRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonStyle: {
    borderRadius: 14,
    backgroundColor: color.slateGray,
    marginBottom: 15,
    marginHorizontal: 20,
  },
  buttonColor: {
    color: color.pencilGray,
  },
  notification: {
    height: 50,
    paddingLeft: 10,
    paddingRight: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerDivider: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  menu: {
    height: 50,
    paddingLeft: 28,
    paddingRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerContainer: {
    flexDirection: 'row',
    backgroundColor: color.blueShade,
  },
  container: {
    flex: 1,
    backgroundColor: color.white,
  },
  // container: {
  //   flex: 1,
  //   backgroundColor: color.white,
  // },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 15,
  },
  // flatlistContainer: {
  //   flexGrow: 1,
  // },

  currentBalance: {
    fontSize: 12,
    fontFamily: font.violetSansRegular,
    color: color.white,
    marginTop: 6,
  },
  currentText: {
    fontSize: 12,
    fontFamily: font.violetSansRegular,
    color: color.black,
    marginTop: 6,
  },
  transactionText: {
    fontSize: 16,
    fontFamily: font.violetSansRegular,
    color: color.black,
    marginTop: 25,
    marginHorizontal: 16,
    marginBottom: 8,
  },
  divider: {
    flexDirection: 'row',
    // justifyContent: 'flex-end',
    alignItems: 'flex-end',
    paddingHorizontal: 20,
    flex: 0.7,
  },
  flexContainer: {
    minHeight: 350,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: color.blueShade,
    marginBottom: 20,
  },
  parent: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  content: {
    // flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: 64,
    height: 64,
    borderRadius: 64 / 2,
    borderWidth: 1,
  },
  loader: {
    height: 250,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: color.borderGray,
  },
  graphContainer: {
    // height: 240,
    marginTop: 10,
  },
  graphStyle: {
    backgroundColor: color.borderGray,
    bottom: 20,
  },
  price: {
    backgroundColor: color.borderGray,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 10,
  },
  graphDivider: {
    flexDirection: 'row',
    marginHorizontal: 17,
  },
  graphTextParent: {
    flex: 1,
    backgroundColor: color.blackTransparent,
    height: 30,
    marginRight: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    marginTop: 10,
  },
  graphText: {
    fontSize: 12,
    fontFamily: font.violetSansRegular,
    color: color.white,
  },
  timeText: {
    fontSize: 8,
    fontFamily: font.violetSansRegular,
    color: color.white,
  },
  rotateImage: {
    transform: [{rotate: '180deg'}],
  },
  timeDivider: {
    flexDirection: 'row',
    backgroundColor: color.green,
    bottom: 20,
  },
  timeContainer: {
    flex: 1,
    height: 30,
    marginRight: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonLabel: {
    fontSize: 14,
    color: color.white,
    fontWeight: '400',
    textAlign: 'center',
  },
  logo: {
    height: 25,
    width: 25,
  },
  logoContainer: {
    height: 50,
    width: 50,
    backgroundColor: color.logoGreen,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
